#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# copy and add .env
.bin/copy-env
git add .env.sample

# copy and add readme
cp README.md docs/README.md
git add docs/README.md

# lint files
npx lint-staged
