name: Update dependencies

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 */5 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm update
          git add package.json package-lock.json
          git commit -m 'chore: updating dependencies'
          git push
