name: Update dependencies

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 */7 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - run: |
          .bin/update-deps
          git add package.json package-lock.json
          npm test
          npm run lint
          npm start
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
